name: flutter_agenda
description: Beautiful Agenda Widget Package for Flutter
version: 1.0.0
homepage: https://github.com/iliyass-zamouri

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
