name: flutter_agenda
description: Agenda Widget Package for Flutter
version: 1.0.4
homepage: https://github.com/iliyass-zamouri/flutter_agenda

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
